apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ambassador-ingress
  namespace: kubeflow
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
    rules:
      - host: ""
        http:
          paths:
            - backend:
                  serviceName: ambassador
                  servicePort: 80
              path: "/"
