---

- name: fetch helm
  get_url:
    url: https://get.helm.sh/{{ helm_archive }}
    dest: "{{ archives_dir }}/{{ helm_archive }}"

- name: uncompress helm
  unarchive:
    src: "{{ archives_dir }}/{{ helm_archive }}"
    remote_src: true
    mode: u+rx
    dest: "~/.local/bin/"

- name: determine if tiller is installed
  shell: >-
    ~/.local/bin/kubectl get pods -n kube-system | grep tiller
  register: tiller_installed
  failed_when: false
  changed_when: false

- name: copy ingress template to the host
  copy:
    src: tiller-rbac.yml
    dest: /tmp/tiller-rbac.yml
  when: tiller_installed.rc != 0

- name: install tiller rbac
  command: kubectl apply -f /tmp/tiller-rbac.yml
  when: tiller_installed.rc != 0

- name: install helm
  shell: |
      set -eu
      helm init --service-account tiller --wait
      kubectl --namespace=kube-system patch deployment tiller-deploy --type=json \
            --patch='[{"op": "add", "path": "/spec/template/spec/containers/0/command", "value": ["/tiller", "--listen=localhost:44134"]}]'
  when: tiller_installed.rc != 0
