---

- name: fetch helm
  get_url:
    url: https://get.helm.sh/{{ helm_archive }}
    dest: "{{ archives_dir }}/{{ helm_archive }}"

- name: uncompress helm archive
  unarchive:
    src: "{{ archives_dir }}/{{ helm_archive }}"
    remote_src: true
    dest: "/tmp/"

- name: copy helm
  copy:
    src: "/tmp/linux-amd64/helm"
    dest: "~/.local/bin/"
    mode: u+rx

- name: initialise tiller
  command: helm init --client-only
