---
- name: fix ingress image
  command: kubectl set image ds/ingress-traefik ingress-traefik-backend=docker.io/traefik:v1.7.17 -n kube-system

- name: copy ingress template to the host
  copy:
    src: ingress-ambassador.yml
    dest: /tmp/ingress-ambassador.yml

- name: install ingress
  command: kubectl apply -f /tmp/ingress-ambassador.yml

- name: get ingress node
  command: kubectl get nodes -o name
  register: ingress_nodes

- name: label a minion as an ingress node
  command: kubectl label {{ item }} role=ingress --overwrite
  with_items: "{{ ingress_nodes }}"
  when: ingress_node in item
