---
- name: determine if kubeflow is installed
  shell: >-
    ~/.local/bin/kubectl get namespace | grep kubeflow
  register: kubeflow_installed
  failed_when: false
  changed_when: false

- name: fetch kfctl
  get_url:
    url: https://github.com/kubeflow/kubeflow/releases/download/{{ kfctl_version }}/kfctl_{{ kfctl_version }}_linux.tar.gz
    dest: "{{ archives_dir }}/{{ kfctl_archive }}"

- name: uncompress kfctl
  unarchive:
    src: "{{ archives_dir }}/{{ kfctl_archive }}"
    remote_src: true
    mode: u+rx
    dest: "~/.local/bin/"

- name: deploy kubeflow
  vars:
    script: |
      set -eu
      export PATH=$PATH:~/.local/bin
      export KFAPP=~/kubeflow
      # Default uses IAP.
      kfctl init ${KFAPP}
      cd ${KFAPP}
      kfctl generate all -V
      kfctl apply all -V
  shell: bash -c "${CMD}"
  environment:
    CMD: "{{ script }}"
  when: kubeflow_installed.rc != 0
  
